name: Run Tests

on:
  workflow_dispatch:  # Manual trigger

jobs:
  wdio:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Set Node.js version to 20

      - name: Install dependencies
        run: npm install

      - name: Run WDIO tests
        run: npm run wdio

      - name: Upload Screenshots
        if: always()  # Upload artifacts even if the previous steps failed
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ./screenshots
