name: Run Tests

on:
  workflow_dispatch:  # Manual trigger

jobs:
  wdio:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Create Screenshots Directory
        run: mkdir -p ./screenshots

      - name: Install dependencies
        run: npm install

      - name: Run WDIO tests
        run: |
          npm run wdio || true

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ./screenshots
